# Generated by Django 4.0.1 on 2022-04-14 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('universityName', models.CharField(max_length=300)),
                ('level_of_Education', models.CharField(choices=[('Choose education Level', 'Choose education Level'), ('Diploma', 'Diploma'), ('Bachelors Degree', 'Bachelors Degree')], default='Choose education Level', max_length=200)),
                ('course_name', models.CharField(max_length=300)),
                ('preferred_company', models.CharField(choices=[('Choose your preferred company', 'Choose your preferred company'), ('Safaricom', 'Safaricom'), ('KPLC', 'KPLC'), ('KenGen', 'KenGen'), ('County Government of Kirinyaga', 'County Government of Kirinyaga'), ('Andela Kenya', 'Andela Kenya'), ('KPA', 'KPA')], default='Choose your preferred company', max_length=300)),
                ('current_location', models.CharField(max_length=300)),
                ('primary_contact', models.IntegerField(blank=True, help_text='example..0712...209', null=True)),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('alternative_contact', models.IntegerField(blank=True, help_text='example..0712...209', null=True)),
                ('School_introduction_Letter', models.FileField(blank=True, help_text='The letter must have an official institution stamp.', null=True, upload_to='files')),
                ('insuarance_cover', models.FileField(blank=True, null=True, upload_to='files')),
                ('Qualified', models.BooleanField()),
                ('attached', models.BooleanField()),
                ('disqualify', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
