# Generated by Django 4.0.1 on 2022-03-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='files',
            new_name='introduction_Letter_and_cover_letter',
        ),
    ]
