# Generated by Django 4.0.1 on 2022-04-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='files',
        ),
    ]
