# Generated by Django 4.0.1 on 2022-04-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_expected_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='expected_start_date',
            new_name='expected_starting_date',
        ),
    ]
