# Generated by Django 4.0.1 on 2022-04-14 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_current_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expected_starting_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
