# Generated by Django 4.0.1 on 2022-04-14 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_school_introduction_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_year_of_study',
            field=models.CharField(default=django.utils.timezone.now, help_text='example..3rd year', max_length=10),
            preserve_default=False,
        ),
    ]
